name: Optimize map and deploy

on:
  push:
    branches:
      - master

jobs:

  deploy-gh-pages:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master

      - name: Commit
        run: |
          ls -al
          git config --global user.email "gh-actions@pablo.tools"
          git config --global user.name "gh-actions"
          git checkout master
          git commit -am "optimized maps"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          BASE_BRANCH: master

      - name: List Files
        run: |
          ls -al
